name: frap_maker
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h516909a_0
  - appdirs=1.4.3=py37h28b3542_0
  - async-timeout=3.0.1=py37_0
  - attrs=19.3.0=py_0
  - bcrypt=3.1.7=py37h8f50634_1
  - biopython=1.77=py37h7b6447c_0
  - blast=2.10.1=pl526he19e7b1_3
  - boost-cpp=1.73.0=h7b93d67_2
  - boto3=1.9.191=py_0
  - botocore=1.12.191=py_0
  - brotlipy=0.7.0=py37h516909a_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.12.8=h06a4308_0
  - cachetools=4.1.0=py_1
  - cairo=1.16.0=h3fc0475_1004
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37hc8dfbb8_1006
  - configargparse=1.2.3=pyh9f0ad1d_0
  - crc32c=2.0=py37h516909a_0
  - cryptography=2.9.2=py37hb09aad4_0
  - curl=7.71.1=hbc83047_1
  - datrie=0.8.2=py37h8f50634_0
  - decorator=4.4.2=py_0
  - docutils=0.16=py37_1
  - dropbox=10.1.2=py37_0
  - entrez-direct=13.9=pl526h375a9b1_0
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.8=py_2
  - flye=2.8.1=py37h8270d21_1
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - ftputil=4.0.0=py_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - ghostscript=9.22=hf484d3e_1001
  - giflib=5.1.9=h516909a_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.3=py_0
  - glib=2.63.1=h3eb4bd4_1
  - google-api-core=1.17.0=py37_0
  - google-api-python-client=1.9.1=pyh9f0ad1d_1
  - google-auth=1.17.2=py_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.28.1=pyh9f0ad1d_0
  - google-resumable-media=0.5.1=pyh9f0ad1d_0
  - googleapis-common-protos=1.51.0=py37_2
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.38.0=hf68f40c_1011
  - harfbuzz=2.4.0=hee91db6_5
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=2.9=py37_0
  - imagemagick=7.0.8_11=pl526hc610aec_0
  - importlib-metadata=1.6.1=py37_0
  - importlib_metadata=1.6.1=0
  - ipython_genutils=0.2.0=py37_0
  - jbig=2.1=h516909a_2002
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - krb5=1.18.2=h173b8e3_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.12.3=hd408876_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=0.5.2=7
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h72b56ed_1
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - markupsafe=1.1.1=py37h8f50634_1
  - multidict=4.7.5=py37h8f50634_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - numpy=1.18.5=py37h8960a57_0
  - oauth2client=4.1.3=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1i=h27cfd23_0
  - pandas=1.0.5=py37h0da4684_0
  - pango=1.40.14=he7ab937_1005
  - paramiko=2.7.1=py37_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pip=20.1.1=py37_1
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - prinseq-plus-plus=1.2.3=h176a8bc_0
  - protobuf=3.12.3=py37he6710b0_0
  - psutil=5.7.0=py37h8f50634_1
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pygraphviz=1.5=py37h8f50634_1002
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.1.0=py37_0
  - pyrsistent=0.16.0=py37h8f50634_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h8f50634_0
  - ratelimiter=1.2.0=py37hc8dfbb8_1001
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - s3transfer=0.2.1=py37_0
  - samtools=1.7=1
  - setuptools=47.3.1=py37hc8dfbb8_0
  - simplejson=3.17.0=py37h8f50634_1
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.19.3=0
  - snakemake-minimal=5.19.3=py_0
  - sqlite=3.32.2=h62c20be_0
  - tk=8.6.10=hed695b0_0
  - toposort=1.5=py_3
  - traitlets=4.3.3=py37hc8dfbb8_1
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.9=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h8f50634_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.4.2=py37h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
